# Copyright (c) 2022--present, The TRIQS/ctseg Authors and their Assignees
# This file is part of TRIQS/ctseg and is licensed under the terms of GPLv3 or later.
# SPDX-License-Identifier: GPL-3.0-or-later
# See LICENSE.txt in the root of this distribution for details.

# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.1.1'
